apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-application
  namespace: default
spec:
  project: default
  source:
    repoURL: https://github.com/soprano37/Terraform_AKS.git
    targetRevision: main
    path: argocd-deployments/manifests
    # Enter your PAT here
    # Example:
    # https://github.com/settings/tokens
    # token: your-generated-token
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
